#!/usr/bin/env bash
# ===========================================================================
#  Paw & Glow — one-command Linux installer (Ubuntu / Debian)
#
#  Run this from the project folder on a fresh VPS:
#
#      sudo bash deploy/setup_server.sh [port]        (default port: 8766)
#
#  It installs the site to /opt/pawandglow, creates a dedicated user, and
#  registers a systemd service that starts on boot and restarts on crash.
#  It also installs a keep-alive cron job (Oracle Always Free instances are
#  reclaimed after 7 idle days — this cron prevents that).
#
#  Re-running is safe: an existing admin-secret.json and uploads/ are
#  preserved (client data is never overwritten).
# ===========================================================================
set -euo pipefail

PORT="${1:-8766}"
SERVICE="pawandglow"
APP_DIR="/opt/pawandglow"
MARKER="${APP_DIR}/.pawandglow-installed"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"

if [ "$(id -u)" -ne 0 ]; then
  echo "Run as root:  sudo bash deploy/setup_server.sh ${PORT}" >&2
  exit 1
fi

if [ "$PROJECT_DIR" = "$APP_DIR" ]; then
  echo "error: you are inside the installed copy (${APP_DIR})." >&2
  echo "       Run this from your original project folder instead." >&2
  exit 1
fi

echo "==> Paw & Glow installer — port ${PORT}"

echo "==> [1/6] Checking Python 3 and curl..."
command -v python3 >/dev/null 2>&1 || {
  echo "    installing python3..."
  apt-get update -y >/dev/null
  apt-get install -y python3 >/dev/null
}
command -v curl >/dev/null 2>&1 || apt-get install -y curl >/dev/null

echo "==> [2/6] Installing site files to ${APP_DIR}..."
if [ -f "$MARKER" ]; then
  echo "    existing install detected — preserving admin-secret.json and uploads/"
  PRESERVE=1
else
  PRESERVE=0
fi
mkdir -p "${APP_DIR}"
cp -r "${PROJECT_DIR}/." "${APP_DIR}/"
rm -rf "${APP_DIR}/deploy" "${APP_DIR}/.git" "${APP_DIR}/.freebuff" \
       "${APP_DIR}/__pycache__" "${APP_DIR}"/desktop-v2.db* \
       "${APP_DIR}/start-tunnel.bat"
if [ "$PRESERVE" -eq 0 ]; then
  rm -rf "${APP_DIR}/admin-secret.json" "${APP_DIR}/uploads"
fi
mkdir -p "${APP_DIR}/uploads"
cp "${SCRIPT_DIR}/keepalive.sh" "${APP_DIR}/keepalive.sh"
chmod +x "${APP_DIR}/keepalive.sh"

echo "==> [3/6] Creating service user..."
if ! id -u pawandglow >/dev/null 2>&1; then
  useradd --system --no-create-home --home-dir "${APP_DIR}" \
          --shell /bin/false pawandglow
fi
chown -R pawandglow:pawandglow "${APP_DIR}"

echo "==> [4/6] Installing systemd service..."
cat > "/etc/systemd/system/${SERVICE}.service" <<EOF
# Generated by deploy/setup_server.sh — edit that script, not this file.
[Unit]
Description=Paw & Glow — website + client CMS
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
User=pawandglow
Group=pawandglow
WorkingDirectory=${APP_DIR}
ExecStart=/usr/bin/python3 ${APP_DIR}/server.py ${PORT}
Restart=always
RestartSec=3
NoNewPrivileges=true
PrivateTmp=true
ProtectSystem=full
ReadWritePaths=${APP_DIR}

[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reload
systemctl enable --now "${SERVICE}"

echo "==> [5/6] Installing keep-alive + backup crons..."
# Per-user crontab format: no user field (these run as root anyway).
# Idle-prevention: hourly CPU/network activity (Oracle reclaims idle free VPS).
KEEPALIVE_LINE="0 * * * * ${APP_DIR}/keepalive.sh # pawandglow-keepalive"
# Safety net: weekly tarball of the only data that changes (content + photos).
BACKUP_LINE="0 3 * * 0 mkdir -p /root/pawandglow-backups && tar czf /root/pawandglow-backups/pawandglow-\$(date +\\%F).tgz -C ${APP_DIR} content.json uploads && find /root/pawandglow-backups -name '*.tgz' -mtime +60 -delete # pawandglow-backup"
( crontab -l 2>/dev/null | grep -v 'pawandglow-keepalive\|pawandglow-backup' || true; echo "${KEEPALIVE_LINE}"; echo "${BACKUP_LINE}" ) | crontab -
echo "    installed cron jobs:"
crontab -l 2>/dev/null | grep -E 'pawandglow-(keepalive|backup)' | sed 's/^/      /' || true

echo "==> [6/6] Verifying service..."
sleep 1
if systemctl is-active --quiet "${SERVICE}"; then
  echo "    service is ACTIVE."
else
  echo "    !!! service did not start — last logs:"
  journalctl -u "${SERVICE}" -n 20 --no-pager || true
fi
touch "$MARKER"
echo
echo "================================================================"
echo " Next steps"
echo "================================================================"
echo " 1) Set the client passcode (takes effect immediately):"
echo "      nano ${APP_DIR}/admin-secret.json"
echo "    (default is 'pawandglow' — CHANGE IT before handover)"
echo
echo " 2) Point the domain at this server — see DEPLOYMENT.md:"
echo "      Recommended: Cloudflare Tunnel -> localhost:${PORT}"
echo "      Alternative: expose port ${PORT} directly"
echo
echo " 3) Point the keepalive at the real domain (hourly cron is already set):"
echo "      sed -i 's#YOUR-DOMAIN.com#theirdomain.com#' ${APP_DIR}/keepalive.sh"
echo "    (or set it now:  nano ${APP_DIR}/keepalive.sh  → KEEPALIVE_URL)"
echo
echo " 4) Backups: a weekly tarball of content.json + uploads lands in"
echo "    /root/pawandglow-backups/ — download it regularly:"
echo "      scp -i ~/.ssh/oracle_key root@<PUBLIC_IP>:/root/pawandglow-backups/*.tgz ."
echo
echo " Useful commands:"
echo "   systemctl status ${SERVICE}       # check the service"
echo "   journalctl -u ${SERVICE} -f       # follow the logs"
echo "   curl http://127.0.0.1:${PORT}/health   # health check"
echo "================================================================"
